### ISSUE TITLE
 Acroforms vs. XFA Forms

### ISSUE THREAD

**Issue by Tadelsucht** [Staubteufel/BulkPDF#18]
System.NullReferenceException: Object reference not set to an instance of an object.
   at BulkPDF.PDF.SaveFilledPDF(String filePath, Boolean finalize)
   at BulkPDF.PDFFiller.CreateFiles(PDF pdf, Boolean finalize, IDataSource dataSource, Dictionary`2 pdfFields, String outputDir, DelGetFilename GetFilename, DelSetPercent setPercent, DelIsAborted isAborted)
   at BulkPDF.MainForm.backGroundWorker_DoWork(Object sender, DoWorkEventArgs e)

If an error like this occures, your pdf must be converted to a BulkPDF compatible specification. For this just upload the file to https://www.pdfescape.com/ , save it there and download it again, without changing anything. The new downloaded file is now compatible with BulkPDF and your configuration should work nicely.

**Comment by ifuchs** [comment]
I have a form which is in XFA format and  (as expected) if I try to use it, BulkPDF says it **will create 0 pdf files**. I tried uploading and downloading from pdfescape.com but the format did not appear to change and I still get that there are 0 forms to fillout. I assume this problem is related to using a pdf in xfa format but perhaps it is something else?

Can anyone help me?

**Comment by ifuchs** [comment]
I tried with an Acroform and I get the same result

**Comment by ifuchs** [comment]
Found the problem. It was not the PDF, it was the spreadsheet. There was a blank line between the header line and the data thus resulting in the program seeing no data. It wold be nice if you could select a range to be used rather than the entire column.
