### ISSUE TITLE
How to set multiline fixed value

### ISSUE THREAD

**Issue by ifuchs** [Staubteufel/BulkPDF#29]
I need to fill-in an address (4 lines) as a fixed field. The app seems to only allow one line. Is there a way to do this?

**Comment by ifuchs** [comment]
If I enter a multiline field using ctrl-enter, the app gives the error:
```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at BulkPDF.PDF.SaveFilledPDF(String filePath, Boolean finalize, Boolean unicode, Boolean customFont, String customFontPath)
   at BulkPDF.PDFFiller.CreateFiles(PDF pdf, Boolean finalize, Boolean unicode, Boolean customFont, String customFontPath, IDataSource dataSource, Dictionary`2 pdfFields, String outputDir, DelGetFilename GetFilename, DelSetPercent setPercent, DelIsAborted isAborted)
   at BulkPDF.MainForm.backGroundWorker_DoWork(Object sender, DoWorkEventArgs e)
```
